# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DotRequest',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('kwota', models.DecimalField(decimal_places=2, help_text='Kwota transakcji  podana z częścią setną.', max_digits=5)),
                ('opis', models.CharField(help_text='Opis przeprowadzanej transakcji. ', max_length=255)),
                ('control', models.CharField(help_text='Parametr kontrolny', max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('added', models.DateTimeField(auto_now_add=True, help_text='Data zamówienia', verbose_name='Data zamówienia')),
            ],
            options={
                'verbose_name_plural': 'Dotpay akcje',
                'verbose_name': 'Dotpay akcja',
            },
        ),
        migrations.CreateModel(
            name='DotResponse',
            fields=[
                ('id_response', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(help_text='ID konta w systemie Dotpay, na rzecz którego dokonywana jest płatność (ID konta Sprzedawcy)')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('FAIL', 'FAIL')], help_text='Informacja o ewentualnym wystąpieniu błędów na stronach serwisu Dotpay', max_length=4)),
                ('control', models.CharField(help_text='Parametr kontrolny jeżeli został podany podczas przekazywania kupującego na strony serwisu Dotpay', max_length=128)),
                ('t_id', models.CharField(help_text='Numer  identyfikacyjny transakcji nadany po księgowaniu na koncie użytkownika Dotpay (Sprzedawcy).', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kwota transakcji. Separatorem dziesiętnym jest znak kropki.', max_digits=5)),
                ('orginal_amount', models.CharField(help_text='Kwota transakcji i znacznik waluty (oddzielone znakiem spacji). Separatorem dziesiętnym jest znak kropki', max_length=100)),
                ('email', models.CharField(help_text='Adres email osoby dokonującej płatność.', max_length=100)),
                ('t_status', models.CharField(choices=[('1', 'NOWA'), ('2', 'WYKONANA'), ('3', 'ODMOWA'), ('4', 'ANULOWANA/ZWROT'), ('5', 'REKLAMACJA')], max_length=1)),
                ('description', models.CharField(blank=True, help_text='Pełna treść opisu transakcji.', max_length=255, null=True)),
                ('md5', models.CharField(max_length=32)),
                ('t_date', models.DateTimeField(auto_now_add=True, help_text='Data otrzymania komunikatu')),
                ('request', models.ForeignKey(help_text='FK dla requestu', on_delete=django.db.models.deletion.CASCADE, to='payment.DotRequest')),
            ],
            options={
                'verbose_name_plural': 'Dotpay odpowiedzi',
                'verbose_name': 'Dotpay odpowiedź',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dotresponse',
            unique_together=set([('t_id', 'control')]),
        ),
    ]
